# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78f625afc145812f422170a951f3909470f3d69bfca5fc876e9c8fcd764131725c24450ac40a5777c60bd48c050eb84782f316d99c2901ddbb59630b37b54088

test:
  secret_key_base: b9f800e9143ce2687d46c05cc5961997edeb11b11bea592d978a9c29db25101daaa3da11e8c96c2aae6ab6ee2ef69926f822ca91df451774c9903465a47fc071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
